---
- hosts: pi
  tasks:
    - name: Setup locales
      locale_gen:
          name: en_US.UTF-8
          state: present
    - name: Ensure package install
      become: true
      apt:
        name: python3-gpiozero
        state: latest
        update_cache: yes
    - name: Copy fancontrol py file
      become: true
      copy:
        src: 'fancontrol.py'
        force: false
        dest: /usr/local/bin/
        mode: +x
    - name: Copy fancontrol sh file
      become: true
      copy:
        src: 'fancontrol.sh'
        force: false
        dest: /etc/init.d/
        mode: +x

    - name: Run fancontrol on restart
      become: true
      cron:
        name: "a job for reboot"
        special_time: reboot
        job: "/etc/init.d/fancontrol.sh start"
